config/routes.rb
Rails.application.routes.draw do
  resources :time_slots
  resources :dancers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # post '/dancers/arrival', to: 'dancers#arrival'

  namespace 'api' do
    resources :time_slots
    resources :dancers
  end

end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
    POLE_IDS = { "upstairs_main" => 0, "upstairs_secondary" => 1, "downstairs_one" => 2, "downstairs_two" => 3, "downstairs_booth" => 4, "downstairs_bar" => 5 }
    $dancer_strings = ["", "", "", "", "", ""]
    has_and_belongs_to_many :dancers


 
    # SETTER & GETTERS
    def upstairs_main=(_name)
        $dancer_strings[0] = _name
        add_dancers
    end
    def upstairs_main
        puts $dancer_strings[0]
        $dancer_strings[0]
    end
    def upstairs_secondary=(_name)
        $dancer_strings[1] = _name
        add_dancers
    end
    def upstairs_secondary
        puts $dancer_strings[1]
        $dancer_strings[1]
    end
    def downstairs_one=(_name)
        $dancer_strings[2] = _name
        add_dancers
    end
    def downstairs_one
        puts $dancer_strings[2]
        $dancer_strings[2]
    end    
    def downstairs_two=(_name)
        $dancer_strings[3] = _name
        add_dancers
    end
    def downstairs_two
        puts $dancer_strings[3]
        $dancer_strings[3]
    end
    def downstairs_booth=(_name)
        $dancer_strings[4] = _name
        add_dancers
    end
    def downstairs_booth
        puts $dancer_strings[4]
        $dancer_strings[4]
    end
    def downstairs_bar=(_name)
        $dancer_strings[5] = _name
        add_dancers
    end
    def downstairs_bar
        puts $dancer_strings[5]
        $dancer_strings[5]
    end


    private
        def add_dancers
            #clear the dancers then reinsert each dancer in order
            self.dancers = []
            $dancer_strings.each do |str|
                self.dancers << Dancer.find_or_create_by(name: str.downcase)
            end
        end
end

app/controllers/api/time_slots_controller.rb
module Api

  class TimeSlotsController < ApplicationController
    
    before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

    # GET /time_slots.json
    def index
      @time_slots = TimeSlot.all
      
      json_response(@time_slots)
    end

    # GET /time_slots/1.json
    def show
    end

    # POST /time_slots
    # POST /time_slots.json
    # TODO: TEST
    def create
      @time_slot = TimeSlot.new(time_slot_params)

      if @time_slot.save
        json_reponse(@time_slot)
      else
        json_repsponse(@time_slot.errors)
      end
    end

    # PATCH/PUT /time_slots/1.json

    def update
      @dancers = @time_slot.dancers
        if @time_slot.update(time_slot_params)
        json_response(@time_slot)
        else
        json_response(@time_slot.errors)
        end
    end

    # DELETE /time_slots/1.json
    def destroy
      if @time_slot.destroy
        render json: "Time Slot Destroyed", status: :ok
      end 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_time_slot
        @time_slot = TimeSlot.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def time_slot_params
        params.permit(:time_slot, :upstairs_main, :upstairs_secondary, :downstairs_one, :downstairs_two, :downstairs_booth, :downstairs_bar, :time)
      end


      

  end
end

app/controllers/time_slots_controller.rb
require 'active_support/core_ext/numeric/time.rb'

class TimeSlotsController < ApplicationController
  


  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = []

    # only display time slots in the future
    TimeSlot.find_each do |ts|
      if (ts.time > DateTime.now - 15.minutes && ts.time < DateTime.now)
        puts "#{ts.time} #{DateTime.now}"
        @now_slot = ts
      end

      if ts.time >= DateTime.now
        @time_slots << ts
      end
    end
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    @dancers = @time_slot.dancers

    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content, message: "Success" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.permit(:time_slot, :upstairs_main, :upstairs_secondary, :downstairs_one, :downstairs_two, :downstairs_booth, :downstairs_bar, :time)
    end

    # def refresh_time_slots
    #   @time_slots = TimeSlot.all( :conditions => ["time >= :now", { :now => DateTime.now }])
    #   # Client.all(:conditions =>
    #   #   ["created_at >= :start_date AND created_at <= :end_date",
    #   #      { :start_date => params[:start_date], :end_date => params[:end_date] }])
    # end
    

end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for @time_slot do |f|%>
  <%= f.time_field :time %>


  <%= f.text_field :upstairs_main %>

  <%= f.text_field :upstairs_secondary %>  

  <%= f.text_field :downstairs_one %>

  <%= f.text_field :downstairs_two %>

  <%= f.text_field :downstairs_booth %>

  <%= f.text_field :downstairs_bar %>

  <%= f.submit "Update" %>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing Time Slot</h1>

<%= render 'form', time_slot: @time_slot %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>First floor Stage</th>
      <th>First floor Podium</th>
      <th>Ground floor Stage</th>
      <th>Ground floor Stage</th>
      <th>Ground floor Booth</th>
      <th>Ground floor Bar</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Dancing Now: </td>
        <% 6.times do |i| %>
          <% if @now_slot != nil &&  @now_slot.dancers[i] != nil && @now_slot.dancers[i].fake_name != "" %>
            <td class="highlight-td"><%= @now_slot.dancers[i].fake_name.capitalize %></td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% @time_slots.each do |time_slot_hash| %>
      <tr>
        <td class="display-time"><%= time_slot_hash.time.strftime("%I:%M %p") %></td>
        <% 6.times do |i| %>
          <% if time_slot_hash.dancers[i] != nil %>
            <td><%= time_slot_hash.dancers[i].fake_name.capitalize %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/time_slots/new.html.erb
<h1>New Time Slot</h1>

<%= render 'form', time_slot: @time_slot %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @time_slot.time %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>