config/routes.rb
Rails.application.routes.draw do
  resources :time_slots
  resources :dancers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # post '/dancers/arrival', to: 'dancers#arrival'

  namespace 'api' do
    resources :time_slots
    resources :dancers
  end

end

app/models/dancer.rb
class Dancer < ApplicationRecord
    has_and_belongs_to_many :time_slots
    after_initialize :set_default_values
  
    def set_default_values
      # Only set if time_zone IS NOT set
      self.present ||= false
    end

    # remove capitalisation from names
    def fake_name=(_name)
        self.name = _name.downcase
    end
    def fake_name
        self.name
    end
end

app/controllers/api/dancers_controller.rb
module Api
  class DancersController < ApplicationController
    before_action :set_dancer, only: [:show, :edit, :update, :destroy]

    #POST /dancers/arrival
    def arrival
      @girl = Dancer.find_or_create_by(name: params[:name] )
    
      respond_to do |format|
        if @girl.update
          format.html { redirect_to @dancer, notice: 'Dancer was successfully updated.' }
          format.json { render :show, status: :ok, location: @dancer }
        else
          format.html { render :edit }
          format.json { render json: @dancer.errors, status: :unprocessable_entity }
        end
      end
    end
    def departure
      @girl = Dancer.find_or_create_by(name: params[:name])
      @girl.present = false
    end


    # GET /dancers
    # GET /dancers.json
    def index
      @dancers = Dancer.all
    end

    # GET /dancers/1
    # GET /dancers/1.json
    def show
    end

    # GET /dancers/new
    def new
      @dancer = Dancer.new
    end

    # GET /dancers/1/edit
    def edit
    end

    # POST /dancers
    # POST /dancers.json
    def create
      @dancer = Dancer.new(dancer_params)

      respond_to do |format|
        if @dancer.save
          format.html { redirect_to @dancer, notice: 'Dancer was successfully created.' }
          format.json { render :show, status: :created, location: @dancer }
        else
          format.html { render :new }
          format.json { render json: @dancer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /dancers/1
    # PATCH/PUT /dancers/1.json
    def update
      respond_to do |format|
        if @dancer.update(dancer_params)
          format.html { redirect_to @dancer, notice: 'Dancer was successfully updated.' }
          format.json { render :show, status: :ok, location: @dancer }
        else
          format.html { render :edit }
          format.json { render json: @dancer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /dancers/1
    # DELETE /dancers/1.json
    def destroy
      @success = "success"
      @failure = "failure"
      if @dancer.destroy
        json_response(@success)
      else
        json_response(@failure)
      end

    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_dancer
        @dancer = Dancer.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def dancer_params
        params.require(:dancer).permit(:name)
      end
  end
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController
  before_action :set_dancer, only: [:show, :edit, :update, :destroy]

  #POST /dancers/arrival
  # def arrival
  #   @girl = Dancer.find_or_create_by(name: params[:name] )

  #   respond_to do |format|
  #     if @girl.update(present: true)
  #       format.html { redirect_to @dancer, notice: 'Dancer was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @dancer }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @dancer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # def departure
  #   @girl = Dancer.find_or_create_by(name: params[:name])
  #   @girl.present = false
  # end


  # GET /dancers
  # GET /dancers.json
  def index
    @dancers = Dancer.all
  end

  # GET /dancers/1
  # GET /dancers/1.json
  def show
  end

  # GET /dancers/new
  def new
    @dancer = Dancer.new
  end

  # GET /dancers/1/edit
  def edit
  end

  # POST /dancers
  # POST /dancers.json
  def create
    @dancer = Dancer.new(dancer_params)

    respond_to do |format|
      if @dancer.save
        format.html { redirect_to @dancer, notice: 'Dancer was successfully created.' }
        format.json { render :show, status: :created, location: @dancer }
      else
        format.html { render :new }
        format.json { render json: @dancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dancers/1
  # PATCH/PUT /dancers/1.json
  def update
    respond_to do |format|
      if @dancer.update(dancer_params)
        format.html { redirect_to @dancer, notice: 'Dancer was successfully updated.' }
        format.json { render :show, status: :ok, location: @dancer }
      else
        format.html { render :edit }
        format.json { render json: @dancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dancers/1
  # DELETE /dancers/1.json
  def destroy
    @dancer.destroy
    respond_to do |format|
      format.html { redirect_to dancers_url, notice: 'Dancer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dancer
      @dancer = Dancer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dancer_params
      params.require(:dancer).permit(:name)
    end
end

app/helpers/dancers_helper.rb
module DancersHelper
end

app/views/dancers/_form.html.erb
<%= form_with(model: dancer, local: true) do |form| %>
  <% if dancer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dancer.errors.count, "error") %> prohibited this dancer from being saved:</h2>

      <ul>
      <% dancer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :dancer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dancers/edit.html.erb
<h1>Editing Dancer</h1>

<%= render 'form', dancer: @dancer %>

<%= link_to 'Show', @dancer %> |
<%= link_to 'Back', dancers_path %>

app/views/dancers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dancers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dancers.each do |dancer| %>
      <tr>
        <td><%= dancer.name %></td>
        <td><%= link_to 'Show', dancer %></td>
        <td><%= link_to 'Edit', edit_dancer_path(dancer) %></td>
        <td><%= link_to 'Destroy', dancer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dancer', new_dancer_path %>

app/views/dancers/new.html.erb
<h1>New Dancer</h1>

<%= render 'form', dancer: @dancer %>

<%= link_to 'Back', dancers_path %>

app/views/dancers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dancer.name %>
</p>

<%= link_to 'Edit', edit_dancer_path(@dancer) %> |
<%= link_to 'Back', dancers_path %>